import type { GuidegramAPI } from '../../electron/preload'
import type {
  AccountInfo,
  DialogItem,
  MessageItem,
  ProxyConfig,
  AppConfig,
  ForwardOptions,
  QrTokenPayload,
  InlineButton,
  ChatDetails,
  WebPagePreview,
  LinkPreviewData,
  ReplyInfo,
  MessageEntityItem,
  MessageReactionItem,
  PinnedMessageItem,
  CloseAction,
  UpdateInfo,
  UpdateProgress,
  OpenFileDialogOptions,
  OpenFileDialogResult,
  SendMediaOptions,
  UploadProgressPayload,
  DownloadProgressPayload,
  BotCallbackResult,
  GlobalSearchResult,
  PortableLocatorInfo,
  ForumTopicItem,
  ScheduledMessageItem,
  StarGiftItem,
  ActiveSessionItem,
  TranslatedTextResult,
  CloudFolderItem,
  StickerItem,
  StickerSetItem,
  StoryItemPayload,
  PeerStoriesPayload,
  ChannelBoostStatus,
  TwoFactorStatus,
  AutoDownloadConfig,
} from '../../electron/telegram/types'

declare global {
  interface Window {
    guidegram: GuidegramAPI
  }
}

export type {
  AccountInfo,
  DialogItem,
  MessageItem,
  ProxyConfig,
  AppConfig,
  ForwardOptions,
  QrTokenPayload,
  InlineButton,
  ChatDetails,
  WebPagePreview,
  LinkPreviewData,
  ReplyInfo,
  MessageEntityItem,
  MessageReactionItem,
  PinnedMessageItem,
  CloseAction,
  UpdateInfo,
  UpdateProgress,
  OpenFileDialogOptions,
  OpenFileDialogResult,
  SendMediaOptions,
  SendMessageOptions,
  UploadProgressPayload,
  DownloadProgressPayload,
  BotCallbackResult,
  CustomEmojiPayload,
  GlobalSearchResult,
  PortableLocatorInfo,
  ForumTopicItem,
  ScheduledMessageItem,
  StarGiftItem,
  ActiveSessionItem,
  TranslatedTextResult,
  CloudFolderItem,
  StickerItem,
  StickerSetItem,
  StoryItemPayload,
  PeerStoriesPayload,
  ChannelBoostStatus,
  TwoFactorStatus,
  AutoDownloadConfig,
}
